version: '3.5'

services:
    app:
        container_name: notification_app
        build:
            context: ./docker/app
            args:
                - timezone=${TZ}
        volumes:
            - ./symfony:/srv:rw,cached
            - app_log:/srv/var/log
        env_file:
            - .env
        environment:
            XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
            PHP_IDE_CONFIG: serverName=${NGINX_HOST}
        networks:
            - app-net
    
    nginx:
        container_name: notification_nginx
        build:
            context: ./docker/nginx
            args:
                - nginx_host=${NGINX_HOST}
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app
        volumes:
            - ./symfony/public:/srv/public:ro
            - ./docker/nginx/default.template:/etc/nginx/conf.d/default.template
            - nginx_log:/var/log/nginx
        env_file:
            - .env
        command: /bin/bash -c "envsubst '$$NGINX_HOST'
            < /etc/nginx/conf.d/default.template
            > /etc/nginx/conf.d/default.conf
            && exec nginx -g 'daemon off;'"
        networks:
            - app-net
    
    postgresql:
        container_name: notification_db
        build:
            context: ./docker/db
            dockerfile: Dockerfile.postgresql
        volumes:
            - ./.data/postgresql:/var/lib/postgresql/data:rw
        env_file:
            - .env
        ports:
            - "5432:5432"
        networks:
            - app-net
    rabbitmq:
        container_name: notification_rabbit
        build:
            context: ./docker/rabbitmq
            args:
                - MANAGEMENT=false
                - FEDERATION=false
                - RABBITMQ_DEFAULT_USER=guest
                - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - app-net
    mail:
        container_name: notification_mail
        restart: unless-stopped
        image: eaudeweb/mailtrap
        ports:
            - "8125:80"
            - "2525:25"
        environment:
            - MT_USER=mailtrap
            - MT_PASSWD=mailtrap
            - MT_MAILBOX_LIMIT=512000001
            - MT_MESSAGE_LIMIT=102400001
        networks:
            - app-net
volumes:
    app_log:
    nginx_log:

networks:
    app-net:
        name: app_network
